### ISSUE TITLE
See if we can directly hit UAB padlock API

### ISSUE THREAD

**Issue by ClaytonBrawley** [rando-6/project#9]

**Comment by andrewpe** [comment]
Sent an email to UAB IT and they assigned it to their "Window's team"

**Comment by ClaytonBrawley** [comment]
Have we made any progress on this?

**Comment by andrewpe** [comment]
Reply back from IT:
John, can you give us more details about what this project entails. Also, information such as what kind of information/data would be published through this application, what OS, app platform, what web server, which server it would be housed would also be helpful.

**Comment by andrewpe** [comment]
My reply:

Hi Rajesh,

The project is for our class CS499 and the idea is most like the https://ideas.uab.edu/ platform avalible. This would be a platform for students to voice their opinions and ideas. Ideas would be moderated and able to be given up votes to boost ideas. What we're are looking for is to integrate with the BlazerID login system to verify the user belongs to the blazerid since our platform will use blazerIDs to identify the user. Currently the server is running on Digital Ocean on a Ubuntu Server but we're talked to the Sysadmin in CIS and he is willing to spin up a Cent OS server running the CIS datacenter on campus. The web server is nginx with a mysql database. The frontend is standard HTML, CSS, JS with the angular.js framework. 

I can supply you with any other information needed, just let me know. 

Thanks,

John T Pearson
Computer Science @ UAB
UAB ACM | Chair
Phone: (205) 586-5168
Email: andrewpe@uab.edu

**Comment by andrewpe** [comment]
Directly hitting the LDAP Server
